services:
  - type: web
    name: malaria-detection-api
    env: docker  # Use Docker environment
    repo: https://github.com/Manideeptheexplorer/malaria-backend
    branch: main  # or whatever branch you're deploying from
    rootDir: backend  # this is where your Dockerfile is
    region: oregon
