services:
  - type: web
    name: malaria-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: MODEL_PATH
        value: ./models/malaria_model.h5
      - key: UPLOAD_DIR
        value: ./uploads
      - key: TEMP_DIR
        value: ./temp
    region: oregon  # or any other Render region
