services:
  - type: web
    name: malaria-detection-api
    env: docker  # ✅ Use docker since you have Dockerfile
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    rootDir: backend  # adjust if your Dockerfile is inside backend/
    region: oregon
