services:
  - type: web
    name: malaria-detection-api
    env: python
    runtime: python
    repo: https://github.com/Manideeptheexplorer/malaria-backend
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    region: oregon
    plan: starter
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MODEL_PATH
        value: ./models/best.pt
      - key: UPLOAD_DIR
        value: ./uploads
      - key: TEMP_DIR
        value: ./temp
    healthCheckPath: /
    autoDeploy: true
